// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SokratisChaimanas/platform-go-challenge/ent/asset"
	"github.com/SokratisChaimanas/platform-go-challenge/ent/favourite"
	"github.com/SokratisChaimanas/platform-go-challenge/ent/predicate"
	"github.com/SokratisChaimanas/platform-go-challenge/ent/user"
	"github.com/google/uuid"
)

// FavouriteUpdate is the builder for updating Favourite entities.
type FavouriteUpdate struct {
	config
	hooks    []Hook
	mutation *FavouriteMutation
}

// Where appends a list predicates to the FavouriteUpdate builder.
func (_u *FavouriteUpdate) Where(ps ...predicate.Favourite) *FavouriteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *FavouriteUpdate) SetUserID(v uuid.UUID) *FavouriteUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *FavouriteUpdate) SetNillableUserID(v *uuid.UUID) *FavouriteUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAssetID sets the "asset_id" field.
func (_u *FavouriteUpdate) SetAssetID(v uuid.UUID) *FavouriteUpdate {
	_u.mutation.SetAssetID(v)
	return _u
}

// SetNillableAssetID sets the "asset_id" field if the given value is not nil.
func (_u *FavouriteUpdate) SetNillableAssetID(v *uuid.UUID) *FavouriteUpdate {
	if v != nil {
		_u.SetAssetID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *FavouriteUpdate) SetUser(v *User) *FavouriteUpdate {
	return _u.SetUserID(v.ID)
}

// SetAsset sets the "asset" edge to the Asset entity.
func (_u *FavouriteUpdate) SetAsset(v *Asset) *FavouriteUpdate {
	return _u.SetAssetID(v.ID)
}

// Mutation returns the FavouriteMutation object of the builder.
func (_u *FavouriteUpdate) Mutation() *FavouriteMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *FavouriteUpdate) ClearUser() *FavouriteUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAsset clears the "asset" edge to the Asset entity.
func (_u *FavouriteUpdate) ClearAsset() *FavouriteUpdate {
	_u.mutation.ClearAsset()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FavouriteUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FavouriteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FavouriteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FavouriteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FavouriteUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Favourite.user"`)
	}
	if _u.mutation.AssetCleared() && len(_u.mutation.AssetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Favourite.asset"`)
	}
	return nil
}

func (_u *FavouriteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(favourite.Table, favourite.Columns, sqlgraph.NewFieldSpec(favourite.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   favourite.UserTable,
			Columns: []string{favourite.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   favourite.UserTable,
			Columns: []string{favourite.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   favourite.AssetTable,
			Columns: []string{favourite.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   favourite.AssetTable,
			Columns: []string{favourite.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{favourite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FavouriteUpdateOne is the builder for updating a single Favourite entity.
type FavouriteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FavouriteMutation
}

// SetUserID sets the "user_id" field.
func (_u *FavouriteUpdateOne) SetUserID(v uuid.UUID) *FavouriteUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *FavouriteUpdateOne) SetNillableUserID(v *uuid.UUID) *FavouriteUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAssetID sets the "asset_id" field.
func (_u *FavouriteUpdateOne) SetAssetID(v uuid.UUID) *FavouriteUpdateOne {
	_u.mutation.SetAssetID(v)
	return _u
}

// SetNillableAssetID sets the "asset_id" field if the given value is not nil.
func (_u *FavouriteUpdateOne) SetNillableAssetID(v *uuid.UUID) *FavouriteUpdateOne {
	if v != nil {
		_u.SetAssetID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *FavouriteUpdateOne) SetUser(v *User) *FavouriteUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetAsset sets the "asset" edge to the Asset entity.
func (_u *FavouriteUpdateOne) SetAsset(v *Asset) *FavouriteUpdateOne {
	return _u.SetAssetID(v.ID)
}

// Mutation returns the FavouriteMutation object of the builder.
func (_u *FavouriteUpdateOne) Mutation() *FavouriteMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *FavouriteUpdateOne) ClearUser() *FavouriteUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAsset clears the "asset" edge to the Asset entity.
func (_u *FavouriteUpdateOne) ClearAsset() *FavouriteUpdateOne {
	_u.mutation.ClearAsset()
	return _u
}

// Where appends a list predicates to the FavouriteUpdate builder.
func (_u *FavouriteUpdateOne) Where(ps ...predicate.Favourite) *FavouriteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FavouriteUpdateOne) Select(field string, fields ...string) *FavouriteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Favourite entity.
func (_u *FavouriteUpdateOne) Save(ctx context.Context) (*Favourite, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FavouriteUpdateOne) SaveX(ctx context.Context) *Favourite {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FavouriteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FavouriteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FavouriteUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Favourite.user"`)
	}
	if _u.mutation.AssetCleared() && len(_u.mutation.AssetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Favourite.asset"`)
	}
	return nil
}

func (_u *FavouriteUpdateOne) sqlSave(ctx context.Context) (_node *Favourite, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(favourite.Table, favourite.Columns, sqlgraph.NewFieldSpec(favourite.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Favourite.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, favourite.FieldID)
		for _, f := range fields {
			if !favourite.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != favourite.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   favourite.UserTable,
			Columns: []string{favourite.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   favourite.UserTable,
			Columns: []string{favourite.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   favourite.AssetTable,
			Columns: []string{favourite.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   favourite.AssetTable,
			Columns: []string{favourite.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Favourite{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{favourite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
