// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Asset is the predicate function for asset builders.
type Asset func(*sql.Selector)

// Favourite is the predicate function for favourite builders.
type Favourite func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
